// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpdljgagjnmiljuryhfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wZGxqZ2Fnam5taWxqdXJ5aGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDk5NDQsImV4cCI6MjA2NTEyNTk0NH0.2BAMCK_tvE_QckKmiOUlZ8er21qv2gD4BFZ_BMTshis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);